from enum import Enum


class Keybinds(str, Enum):
    MOVE_DOWN = "move down"
    SHIFT_DOWN = "shift down"
    MOVE_UP = "move up"
    SHIFT_UP = "shift up"
    TOGGLE_COMPLETE = "toggle complete"
    COPY_TEXT = "copy text"
    YANK = "yank"
    PASTE = "paste"
    MOVE_TO_TOP = "move to top"
    MOVE_TO_BOTTOM = "move to bottom"
    TOGGLE_EXPAND = "toggle expand"
    TOGGLE_EXPAND_RECURSIVE = "toggle expand recursive"
    TOGGLE_EXPAND_PARENT = "toggle expand parent"
    REMOVE_ITEM = "remove item"
    ADD_SIBLING = "add sibling"
    ADD_CHILD = "add child"
    SORT_MENU_TOGGLE = "sort menu toggle"
    START_SEARCH = "start search"
    SWITCH_PANE = "switch pane"
    SWITCH_PANE_WORKSPACE = "switch pane workspace"
    SWITCH_PANE_TODO = "switch pane todo"
    EDIT_DUE = "edit due"
    EDIT_DESCRIPTION = "edit description"
    EDIT_EFFORT = "edit effort"
    EDIT_RECURRENCE = "edit recurrence"
    SWITCH_DATE_STYLE = "switch date style"
    INCREASE_URGENCY = "increase urgency"
    DECREASE_URGENCY = "decrease urgency"
    SPAWN_HELP = "spawn help"
